sudo: required
services: docker
install:
- docker-compose -f docker-compose.tests.yml -p ci build
script:
- docker-compose -f docker-compose.tests.yml -p ci run web-tests python -m pytest
  --cov=web/ tests --configfile=configtestdocker
- docker-compose -f docker-compose.tests.yml -p ci run web-tests /bin/bash -c "curl
  -s https://codecov.io/env -o cc_env.sh; bash cc_env.sh; curl -s https://codecov.io/bash
  -o cc_bash.sh; bash cc_bash.sh -t 29296fa1-102b-41a1-880a-adc2bcc99e20"
env:
  global:
  - secure: xBbL4i+IpSNT0hlF7Qt9gWV4eWMJfqW1hBAweZ4fMKIHcHwkpg1BI+4L9iDgvUdLopvVyGwsdBQOxxzZisRX34PFJD41qs1PLhzdsifDg8RfXNIjG/tUY7oD3rD0mPq2JWTkXGtto3OTdKNZK9wb8MK+m24/wc6MIVAnZxqtI5dWZDnAMxW/tWidpmz0h3UdlIG2ya6VDDee4Q/tAhsjws/Pr1Pz1V2nEWgOpsIY1T0Z2RBGB1hVGYtmMQz+0LHY7ZBa+qlcIV06vqe9YoD5Os8Um+Cj5LiIjPUNSIdsXYzwZGTFnXFxeJtBKSv6BUMB+I/HF3z+5R47ngubV1xbWjyaBhhTdU38TRgRReo155XOyp97ielrCbInzCSajMDXfBkCcx9ZNfTw125aQyQ//cmduClonB6/YDQelSEixVHYM4zUkldI1/KExIgCAv8AxXY6ZXgs2NsbvTWZMHmDIzFEgGCSJNNyyeRITF+tw1G6XBd+VMqhaTDa7hbD+FfgpNYLMbhF5pQpO9aXm7TYQ5MqAb0G6wVCOrbLrnnXt/7WWnaMaoZHuJIgJ1fM8gqx92rjPT3bHLg/Q9DFXn6IWolDCzv7fmpjsiYU9tyC7Mz1vwOONvjRBJY/BzcRdh/6vquL7tiTusMcxPkq832vt6kgr6vcIxM8Yzuwri3otQY=
  - secure: rEEYYu4biiEfHNqvcfdxXby66cegKNUwZqJhU/kQ6jA53s80muzYvVpUf5rol8074RfqkORytxzDdwbsQR2JgsPmh/rm36+IX+DS+UxUgI1QpSuJoc2aHtiI4yIrgwHF6vqt85EbLOzSxZEYdvXZGK/LbdbJEbjTWlFPuR62qbp5bSh9Pc0Kl15oLQc9ZLkcIcLlnELP6P1eb0oTkoEqBVdv7k/PMLyd+FhGa3Cg6dj2Ld7AwmB0swmjcnYHRT5KGRffxPW9HEwjjDAM6UWqY6G01wp4rrEelfQJQJzt4aGNUs/9qhdVz/ENv4r7G1wdGYxgME8PV5r4TntzYNtdiWzrD3zXuC9DD/S3gFaLnrFtatRfRzqHEyDLumDS4LKx/hk6/ACHf8ZSTNg9Vsp2ThgCK4oQESODtOMLya+k93ZeJle7LJ7FEqSdZdt+EgumSv+Z1xHW8uoQbINSMwqFF7FedqCOLR6WivUTJ0Ln8UTAFeXwLBQM7DMDN6U/trbN2FlURsc8dyaiAs+zc9kPIjsVCViOVuyLQk0mJ9TXi/cBwM6zbWUI38Qd6DMrm2dPf8z7VbJzs143itDPHpUNFFrPz7jE67rsPfJ1yRikPtLgZAGvfGnTpavXdOUAgn2OTcaGWfCQIyGIQ3KU4BJwBu7z26HB4J3eDgPf1jCyMmY=

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master